apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: observability
  labels:
    app: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - observability
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.8.22 #Log4Shell CVE not detected by DockerHub
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-svc:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: observability
  labels:
    app: kibana
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana

